Create directory
freeserverproject/freeserver-wiki pull request #116
Opened 2022-03-10 08:34 UTC by A-B-S-I

**ディレクトリの変更が多岐に渡るため、ページリンクの貼り直しが必要になる。**

world直下に、文字通り住所のようにデータベース化。建物毎に登録する。
transportのみ、エリアを跨ぐために独立させた。路線等はtransportに、駅本体は置かれているエリアの方に記述する。
施設の自体の分類毎のページはfacility-indexに集約する。
→複合施設等にも対応できる

2022-03-10 11:07 UTC, graycat27 commented
[farm.md](https://github.com/freeserverproject/freeserver-wiki/pull/116/files#diff-72e4d3a42c4a7e1ca06390bd6867d31fba440999c104e69532a42fd982c94b44)
[ranch.md](https://github.com/freeserverproject/freeserver-wiki/pull/116/files#diff-49199707237e37957276d3535bd15f6511a081a329b75c7d7c701fcf5f3d7dac)
[tourism.md](https://github.com/freeserverproject/freeserver-wiki/pull/116/files#diff-c5e822f296aa9933a51952dbd8b2cbb42c1ae61f7a2cc8341361dd093a5d8c3d)
[transport.md](https://github.com/freeserverproject/freeserver-wiki/pull/116/files#diff-f3ce40d814b2426ae961e839f0111f056e166fa2ace9123b2e37ff9ac9af7297)
[trap.md](https://github.com/freeserverproject/freeserver-wiki/pull/116/files#diff-505603c4de0a280ef5940b57282fd04ceef110a7ac191733ace471cdaf176e88)
[tree.md](https://github.com/freeserverproject/freeserver-wiki/pull/116/files#diff-e714563ab767f5688456a5809483a53301e1e45844b30bb944426bcd3646bb09)
index以外の仮置きされてるファイルたち、仮書きとはいってもどんな情報を集約したいのか書いてほしいにゃ
ちなみに[trapは既存記事がある](https://github.com/freeserverproject/freeserver-wiki/blob/master/docs/world/mobtrap.md)ので置き換えるのかな

2022-03-10 11:09 UTC, graycat27 commented on docs/world/index.md
> +|[メインワールド](./main/)|スポーンしたときのワールド。|
/world/main.html の書式が好ましいと思う（相対パスの方が構成変更時に修正がめんどくさい）

2022-03-10 11:10 UTC, A-B-S-I commented
農場
牧場
観光
交通
トラップ
植林
の順にゃ。
あとで中に書いておくにゃ。

分類で増やせるようにするのはこの形が適よな？

2022-03-10 11:15 UTC, graycat27 commented
構成をtreeコマンドで抜き出してきた。これを見て考えます()
```
└─world
    │  art-world.md
    │  FSSF2021.md
    │  index.md
    │  mobtrap.md
    │  seichi.md
    │  shigen.md
    │  
    └─main
        │  index.md
        │  
        ├─overworld
        │  │  overworld-area-template.md
        │  │  
        │  ├─momizidani
        │  │      index.md
        │  │      keidoro.md
        │  │      quiz-rally.md
        │  │      takarakuzi.md
        │  │      
        │  ├─spawn
        │  │      index.md
        │  │      
        │  └─transport
        │          index.md
        │          
        ├─nether
        │  │  nether-area-template.md
        │  │  
        │  ├─spawn
        │  │      index.md
        │  │      
        │  └─transport
        │          index.md
        │          
        ├─the-end
        │  │  the-end-area-template.md
        │  │  
        │  ├─spawn
        │  │      facility.md
        │  │      index.md
        │  │      
        │  └─transport
        │          index.md
        │          
        └─world-template
            ├─area-template
            │      facility.md
            │      index.md
            │      station.md
            │      trap.md
            │      
            └─transport-template
                    index.md
                    road-template.md
                    train-template.md
                    └─world
```

2022-03-10 11:19 UTC, A-B-S-I commented on docs/world/index.md
> +|[メインワールド](./main/)|スポーンしたときのワールド。|
絶対パスに書き直せば良いってことねー？

2022-03-10 11:32 UTC, graycat27 commented
```
    │  art-world.md
    │  seichi.md
    │  shigen.md
```
これらも、main配下で独立フォルダ化して、index.md としておくのが良いかも？
そのワールド内の特殊施設が増えることは…あまり考えられないけど、構成的に統一した方がいいのかな、と。

2022-03-10 11:32 UTC, graycat27 commented
```
    │  FSSF2021.md
```
これは `main/summerFestival/2021.md` とか

2022-03-10 11:36 UTC, graycat27 commented on docs/world/index.md
> +|[メインワールド](./main/)|スポーンしたときのワールド。|
yes sir

2022-03-10 11:37 UTC, graycat27 commented
> main配下で独立フォルダ化

これは、「main」の意図を私が読み違えたかもしれにゃい。「メインワールド」を意図してるなら、配下に入れるのは違うわね

2022-03-10 11:38 UTC, graycat27 commented
ディレクトリ構成、特に既にmain配下に入れてあるものについては、このPRの構成で良いと思います

2022-03-10 14:10 UTC, A-B-S-I commented
メインワールドを意図しているので、そうね、その周りは変更しない方針で。
ただ、event/summerfestival/2021.mdとするのはありかもしれない。あるいは過去のワールドは別所でまとめるでも。

2022-03-10 17:44 UTC, tsutoringo requested changes

2022-03-10 17:44 UTC, tsutoringo commented on docs/world/index.md
> +|[メインワールド](./main/)|スポーンしたときのワールド。|
結局ここまだ直してないです

2022-03-11 01:04 UTC, A-B-S-I commented on docs/world/index.md
> +|[メインワールド](./main/)|スポーンしたときのワールド。|
わーすーれーてーたー

2022-03-11 09:45 UTC, graycat27 commented on docs/world/index.md
> +|[メインワールド](freeserver-wiki/docs/world/main/)|スポーンしたときのワールド。|
`freeserver-wiki/docs` 要るんすか？

2022-03-11 09:46 UTC, A-B-S-I commented on docs/world/index.md
> +|[メインワールド](freeserver-wiki/docs/world/main/)|スポーンしたときのワールド。|
絶対パスにするって話を実行しようとしたが、うまくいっていないらしい

2022-03-11 09:59 UTC, tsutoringo approved these changes

2022-03-11 10:10 UTC, merged